### ISSUE TITLE
[BE] FIX: 멤버 첫 로그인 시 정보 변경 

### ISSUE THREAD

**Issue by eunbi9n** [42EASY/PongPongPingPong#145]
## 수정할 코드 설명
첫 로그인 -> 프로필 설정 시 문제가 생길만한 코드가 많아 해당 부분을 수정하려고 합니다.

## Todo
- [x] 기본 프로필 이미지 경로 추가
- [x] 닉네임 랜덤값으로 저장
- [x] 닉네임 조건 설정(15자 이내, 한글, 영어, 숫자)
